wxshop:
    orderservice:
        version: 0.0.1

dubbo:
    registry:
        address: zookeeper://127.0.0.1:2181
    scan:
        base-packages: com.westee.order.service;
spring:
    application:
        name: wxshop-order